### PR TITLE
Updated to work with OBS pause, and add separate timers for stream and record.

### PR DESCRIPTION
**Pull request by TheTawnyFool**
Hi, this is my first time working on a project in github.  Please let me know if I'm not doing anything in a way that is incorrect or considered inappropriate.  

## Changed timers
     Changed the output to log separate timers for recording and streaming. Allows for independent timestamps of streaming and recordings at the same time. 

## Update for OBS pause functionality
     Updated to fix problems with OBS update to allow pausing in recordings.  Now when you pause a recording, the recording timer used by the hotkeys will pause until you resume the recording.  This way the record timer offsets of the hotkey events to be synced correctly with the video. The streaming timer will not pause if you are tracking both.

## Checkbox to log streaming events
      Allows turning on and off logging relating to streaming. Recommend to leave off if not streaming, and or not wanting to log timers relating to streaming.

### CODE REVIEW

**Comment by TheTawnyFool** [comment]
Hmm, I programmed and built this in windows.  Which was new to me because all my experience in past was linux.  I'll have to build a linux virtual machine and get everything set up to see why its not compiling in linux.

**Comment by TheTawnyFool** [comment]
While I'm setting all that up, I'm guessing its because you have an old version of OBS, before those API functions were added to obs (release OBS 24.0 I think).  Its only a couple months old.
Do I need to make the plug in work with old versions?  This is my first github so not clear on a few things, sorry.

**Comment by TheTawnyFool** [comment]
I got it to compile without much issue in linux.  I did remove -lobs -lobs-frontend-api flags from makefile.linux, that is after your error anyway.

I'm pretty sure you are using an old version of OBS so its not finding the newer declarations.  Like I said I am new to github, so not sure how to run it in the exact environment you have.  

I see you are using docker and showing a config and build file, is there a tutorial somewhere showing me how to take those and run in your envirnment.  This might be a common thing I'm missing.  I'm brand new to github and open source like this.

Thanks

**Comment by partouf** [comment]
Hi! Thanks so much for the contribution!

Don't worry about the travis build, I'll fix it.

Do you have an idea when the OBS_FRONTEND_EVENT_RECORDING_PAUSED / OBS_FRONTEND_EVENT_RECORDING_UNPAUSED events were introduced? I'll have to change the plugins' supported version on the obs plugins webpage..

**Comment by TheTawnyFool** [comment]
Hi!  Yes, I left a note on the failed build error in the github part, I'm hoping you can get those.  Getting use to best github practices.
  It looks like the obs-studio release 24 is when pausing was introduced.  It released around the beginning of September.
  Thanks!
-Tony

    On Friday, November 22, 2019, 4:57:27 AM CST, Patrick Quist <notifications@github.com> wrote:  
 
 
Hi! Thanks so much for the contribution!

Don't worry about the travis build, I'll fix it.

Do you have an idea when the OBS_FRONTEND_EVENT_RECORDING_PAUSED / OBS_FRONTEND_EVENT_RECORDING_UNPAUSED events were introduced? I'll have to change the plugins' supported version on the obs plugins webpage..

**Comment by TheTawnyFool** [comment]
Need anymore help with this.  Like compiling different versions for download etc?  Just let me know.
Thanks!

**Pull request merged**
